# Generated by Django 4.1.1 on 2022-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=models.TextField(default=''),
        ),
    ]
