# Generated by Django 4.1.1 on 2022-09-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('calc_date', models.DateField(unique=True)),
                ('calc_result', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Celeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('birthday', models.DateField()),
                ('persid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CelebData',
            fields=[
                ('celeb', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='numero.celeb')),
                ('profession', models.CharField(max_length=190)),
                ('profile_url', models.URLField(max_length=255)),
                ('photo_url', models.URLField(max_length=255)),
            ],
        ),
    ]
