# Generated by Django 4.1.1 on 2022-09-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katysite', '__first__'),
        ('numero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('slug', models.SlugField(unique=True)),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='katysite.mainmenu')),
            ],
        ),
    ]
